package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * AbonnementId generated by hbm2java
 */
public class AbonnementId implements java.io.Serializable {

	private int idService;
	private int idAbonnee;

	public AbonnementId() {
	}

	public AbonnementId(int idService, int idAbonnee) {
		this.idService = idService;
		this.idAbonnee = idAbonnee;
	}

	public int getIdService() {
		return this.idService;
	}

	public void setIdService(int idService) {
		this.idService = idService;
	}

	public int getIdAbonnee() {
		return this.idAbonnee;
	}

	public void setIdAbonnee(int idAbonnee) {
		this.idAbonnee = idAbonnee;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbonnementId))
			return false;
		AbonnementId castOther = (AbonnementId) other;

		return (this.getIdService() == castOther.getIdService())
				&& (this.getIdAbonnee() == castOther.getIdAbonnee());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdService();
		result = 37 * result + this.getIdAbonnee();
		return result;
	}

}
