package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * Abonnement generated by hbm2java
 */
public class Abonnement implements java.io.Serializable {

	private AbonnementId id;
	private Service service;
	private Abonnee abonnee;

	public Abonnement() {
	}

	public Abonnement(AbonnementId id, Service service, Abonnee abonnee) {
		this.id = id;
		this.service = service;
		this.abonnee = abonnee;
	}

	public AbonnementId getId() {
		return this.id;
	}

	public void setId(AbonnementId id) {
		this.id = id;
	}

	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	public Abonnee getAbonnee() {
		return this.abonnee;
	}

	public void setAbonnee(Abonnee abonnee) {
		this.abonnee = abonnee;
	}

}
