package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Abonnee generated by hbm2java
 */
public class Abonnee implements java.io.Serializable {

	private Integer idAbonnee;
	private String nomAbonnee;
	private String telAbonnee;
	private String emailAbonnee;
	private String passwordAbonnee;
	private Set abonnements = new HashSet(0);

	public Abonnee() {
	}

	public Abonnee(String nomAbonnee, String telAbonnee, String emailAbonnee,
			String passwordAbonnee) {
		this.nomAbonnee = nomAbonnee;
		this.telAbonnee = telAbonnee;
		this.emailAbonnee = emailAbonnee;
		this.passwordAbonnee = passwordAbonnee;
	}

	public Abonnee(String nomAbonnee, String telAbonnee, String emailAbonnee,
			String passwordAbonnee, Set abonnements) {
		this.nomAbonnee = nomAbonnee;
		this.telAbonnee = telAbonnee;
		this.emailAbonnee = emailAbonnee;
		this.passwordAbonnee = passwordAbonnee;
		this.abonnements = abonnements;
	}

	public Integer getIdAbonnee() {
		return this.idAbonnee;
	}

	public void setIdAbonnee(Integer idAbonnee) {
		this.idAbonnee = idAbonnee;
	}

	public String getNomAbonnee() {
		return this.nomAbonnee;
	}

	public void setNomAbonnee(String nomAbonnee) {
		this.nomAbonnee = nomAbonnee;
	}

	public String getTelAbonnee() {
		return this.telAbonnee;
	}

	public void setTelAbonnee(String telAbonnee) {
		this.telAbonnee = telAbonnee;
	}

	public String getEmailAbonnee() {
		return this.emailAbonnee;
	}

	public void setEmailAbonnee(String emailAbonnee) {
		this.emailAbonnee = emailAbonnee;
	}

	public String getPasswordAbonnee() {
		return this.passwordAbonnee;
	}

	public void setPasswordAbonnee(String passwordAbonnee) {
		this.passwordAbonnee = passwordAbonnee;
	}

	public Set getAbonnements() {
		return this.abonnements;
	}

	public void setAbonnements(Set abonnements) {
		this.abonnements = abonnements;
	}

}
