package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * CodeAcces generated by hbm2java
 */
public class CodeAcces implements java.io.Serializable {

	private Integer idCodeAcces;
	private Marchand marchand;
	private String codeAcces;
	private int validite;

	public CodeAcces() {
	}

	public CodeAcces(Marchand marchand, String codeAcces, int validite) {
		this.marchand = marchand;
		this.codeAcces = codeAcces;
		this.validite = validite;
	}

	public Integer getIdCodeAcces() {
		return this.idCodeAcces;
	}

	public void setIdCodeAcces(Integer idCodeAcces) {
		this.idCodeAcces = idCodeAcces;
	}

	public Marchand getMarchand() {
		return this.marchand;
	}

	public void setMarchand(Marchand marchand) {
		this.marchand = marchand;
	}

	public String getCodeAcces() {
		return this.codeAcces;
	}

	public void setCodeAcces(String codeAcces) {
		this.codeAcces = codeAcces;
	}

	public int getValidite() {
		return this.validite;
	}

	public void setValidite(int validite) {
		this.validite = validite;
	}

}
