package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * MarchandEntrepriseId generated by hbm2java
 */
public class MarchandEntrepriseId implements java.io.Serializable {

	private int idMarchand;
	private String nomEntreprise;
	private String paysEntreprise;
	private String formeJuridique;
	private String numeroEnreg;
	private String addressEntreprise;
	private String siteEntreprise;
	private String appEntreprise;

	public MarchandEntrepriseId() {
	}

	public MarchandEntrepriseId(int idMarchand, String nomEntreprise,
			String paysEntreprise, String formeJuridique, String numeroEnreg,
			String addressEntreprise) {
		this.idMarchand = idMarchand;
		this.nomEntreprise = nomEntreprise;
		this.paysEntreprise = paysEntreprise;
		this.formeJuridique = formeJuridique;
		this.numeroEnreg = numeroEnreg;
		this.addressEntreprise = addressEntreprise;
	}

	public MarchandEntrepriseId(int idMarchand, String nomEntreprise,
			String paysEntreprise, String formeJuridique, String numeroEnreg,
			String addressEntreprise, String siteEntreprise,
			String appEntreprise) {
		this.idMarchand = idMarchand;
		this.nomEntreprise = nomEntreprise;
		this.paysEntreprise = paysEntreprise;
		this.formeJuridique = formeJuridique;
		this.numeroEnreg = numeroEnreg;
		this.addressEntreprise = addressEntreprise;
		this.siteEntreprise = siteEntreprise;
		this.appEntreprise = appEntreprise;
	}

	public int getIdMarchand() {
		return this.idMarchand;
	}

	public void setIdMarchand(int idMarchand) {
		this.idMarchand = idMarchand;
	}

	public String getNomEntreprise() {
		return this.nomEntreprise;
	}

	public void setNomEntreprise(String nomEntreprise) {
		this.nomEntreprise = nomEntreprise;
	}

	public String getPaysEntreprise() {
		return this.paysEntreprise;
	}

	public void setPaysEntreprise(String paysEntreprise) {
		this.paysEntreprise = paysEntreprise;
	}

	public String getFormeJuridique() {
		return this.formeJuridique;
	}

	public void setFormeJuridique(String formeJuridique) {
		this.formeJuridique = formeJuridique;
	}

	public String getNumeroEnreg() {
		return this.numeroEnreg;
	}

	public void setNumeroEnreg(String numeroEnreg) {
		this.numeroEnreg = numeroEnreg;
	}

	public String getAddressEntreprise() {
		return this.addressEntreprise;
	}

	public void setAddressEntreprise(String addressEntreprise) {
		this.addressEntreprise = addressEntreprise;
	}

	public String getSiteEntreprise() {
		return this.siteEntreprise;
	}

	public void setSiteEntreprise(String siteEntreprise) {
		this.siteEntreprise = siteEntreprise;
	}

	public String getAppEntreprise() {
		return this.appEntreprise;
	}

	public void setAppEntreprise(String appEntreprise) {
		this.appEntreprise = appEntreprise;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MarchandEntrepriseId))
			return false;
		MarchandEntrepriseId castOther = (MarchandEntrepriseId) other;

		return (this.getIdMarchand() == castOther.getIdMarchand())
				&& ((this.getNomEntreprise() == castOther.getNomEntreprise()) || (this
						.getNomEntreprise() != null
						&& castOther.getNomEntreprise() != null && this
						.getNomEntreprise()
						.equals(castOther.getNomEntreprise())))
				&& ((this.getPaysEntreprise() == castOther.getPaysEntreprise()) || (this
						.getPaysEntreprise() != null
						&& castOther.getPaysEntreprise() != null && this
						.getPaysEntreprise().equals(
								castOther.getPaysEntreprise())))
				&& ((this.getFormeJuridique() == castOther.getFormeJuridique()) || (this
						.getFormeJuridique() != null
						&& castOther.getFormeJuridique() != null && this
						.getFormeJuridique().equals(
								castOther.getFormeJuridique())))
				&& ((this.getNumeroEnreg() == castOther.getNumeroEnreg()) || (this
						.getNumeroEnreg() != null
						&& castOther.getNumeroEnreg() != null && this
						.getNumeroEnreg().equals(castOther.getNumeroEnreg())))
				&& ((this.getAddressEntreprise() == castOther
						.getAddressEntreprise()) || (this
						.getAddressEntreprise() != null
						&& castOther.getAddressEntreprise() != null && this
						.getAddressEntreprise().equals(
								castOther.getAddressEntreprise())))
				&& ((this.getSiteEntreprise() == castOther.getSiteEntreprise()) || (this
						.getSiteEntreprise() != null
						&& castOther.getSiteEntreprise() != null && this
						.getSiteEntreprise().equals(
								castOther.getSiteEntreprise())))
				&& ((this.getAppEntreprise() == castOther.getAppEntreprise()) || (this
						.getAppEntreprise() != null
						&& castOther.getAppEntreprise() != null && this
						.getAppEntreprise()
						.equals(castOther.getAppEntreprise())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMarchand();
		result = 37
				* result
				+ (getNomEntreprise() == null ? 0 : this.getNomEntreprise()
						.hashCode());
		result = 37
				* result
				+ (getPaysEntreprise() == null ? 0 : this.getPaysEntreprise()
						.hashCode());
		result = 37
				* result
				+ (getFormeJuridique() == null ? 0 : this.getFormeJuridique()
						.hashCode());
		result = 37
				* result
				+ (getNumeroEnreg() == null ? 0 : this.getNumeroEnreg()
						.hashCode());
		result = 37
				* result
				+ (getAddressEntreprise() == null ? 0 : this
						.getAddressEntreprise().hashCode());
		result = 37
				* result
				+ (getSiteEntreprise() == null ? 0 : this.getSiteEntreprise()
						.hashCode());
		result = 37
				* result
				+ (getAppEntreprise() == null ? 0 : this.getAppEntreprise()
						.hashCode());
		return result;
	}

}
