package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Marchand generated by hbm2java
 */
public class Marchand implements java.io.Serializable {

	private Integer idMarchand;
	private String nomMarchand;
	private String prenomMarchand;
	private String titreMarchand;
	private String emailMarchand;
	private String passwordMarchand;
	private String situationProMarchand;
	private Date dateNMarchand;
	private String paysMarchand;
	private String addressMarchand;
	private String nationalite;
	private String telMarchand;
	private boolean siteApp;
	private Set codeAcceses = new HashSet(0);
	private Set marchandEntreprises = new HashSet(0);
	private Set marchandAssociations = new HashSet(0);

	public Marchand() {
	}

	public Marchand(String nomMarchand, String prenomMarchand,
			String titreMarchand, String emailMarchand,
			String passwordMarchand, String situationProMarchand,
			Date dateNMarchand, String paysMarchand, String addressMarchand,
			String nationalite, String telMarchand, boolean siteApp) {
		this.nomMarchand = nomMarchand;
		this.prenomMarchand = prenomMarchand;
		this.titreMarchand = titreMarchand;
		this.emailMarchand = emailMarchand;
		this.passwordMarchand = passwordMarchand;
		this.situationProMarchand = situationProMarchand;
		this.dateNMarchand = dateNMarchand;
		this.paysMarchand = paysMarchand;
		this.addressMarchand = addressMarchand;
		this.nationalite = nationalite;
		this.telMarchand = telMarchand;
		this.siteApp = siteApp;
	}

	public Marchand(String nomMarchand, String prenomMarchand,
			String titreMarchand, String emailMarchand,
			String passwordMarchand, String situationProMarchand,
			Date dateNMarchand, String paysMarchand, String addressMarchand,
			String nationalite, String telMarchand, boolean siteApp,
			Set codeAcceses, Set marchandEntreprises, Set marchandAssociations) {
		this.nomMarchand = nomMarchand;
		this.prenomMarchand = prenomMarchand;
		this.titreMarchand = titreMarchand;
		this.emailMarchand = emailMarchand;
		this.passwordMarchand = passwordMarchand;
		this.situationProMarchand = situationProMarchand;
		this.dateNMarchand = dateNMarchand;
		this.paysMarchand = paysMarchand;
		this.addressMarchand = addressMarchand;
		this.nationalite = nationalite;
		this.telMarchand = telMarchand;
		this.siteApp = siteApp;
		this.codeAcceses = codeAcceses;
		this.marchandEntreprises = marchandEntreprises;
		this.marchandAssociations = marchandAssociations;
	}

	public Integer getIdMarchand() {
		return this.idMarchand;
	}

	public void setIdMarchand(Integer idMarchand) {
		this.idMarchand = idMarchand;
	}

	public String getNomMarchand() {
		return this.nomMarchand;
	}

	public void setNomMarchand(String nomMarchand) {
		this.nomMarchand = nomMarchand;
	}

	public String getPrenomMarchand() {
		return this.prenomMarchand;
	}

	public void setPrenomMarchand(String prenomMarchand) {
		this.prenomMarchand = prenomMarchand;
	}

	public String getTitreMarchand() {
		return this.titreMarchand;
	}

	public void setTitreMarchand(String titreMarchand) {
		this.titreMarchand = titreMarchand;
	}

	public String getEmailMarchand() {
		return this.emailMarchand;
	}

	public void setEmailMarchand(String emailMarchand) {
		this.emailMarchand = emailMarchand;
	}

	public String getPasswordMarchand() {
		return this.passwordMarchand;
	}

	public void setPasswordMarchand(String passwordMarchand) {
		this.passwordMarchand = passwordMarchand;
	}

	public String getSituationProMarchand() {
		return this.situationProMarchand;
	}

	public void setSituationProMarchand(String situationProMarchand) {
		this.situationProMarchand = situationProMarchand;
	}

	public Date getDateNMarchand() {
		return this.dateNMarchand;
	}

	public void setDateNMarchand(Date dateNMarchand) {
		this.dateNMarchand = dateNMarchand;
	}

	public String getPaysMarchand() {
		return this.paysMarchand;
	}

	public void setPaysMarchand(String paysMarchand) {
		this.paysMarchand = paysMarchand;
	}

	public String getAddressMarchand() {
		return this.addressMarchand;
	}

	public void setAddressMarchand(String addressMarchand) {
		this.addressMarchand = addressMarchand;
	}

	public String getNationalite() {
		return this.nationalite;
	}

	public void setNationalite(String nationalite) {
		this.nationalite = nationalite;
	}

	public String getTelMarchand() {
		return this.telMarchand;
	}

	public void setTelMarchand(String telMarchand) {
		this.telMarchand = telMarchand;
	}

	public boolean isSiteApp() {
		return this.siteApp;
	}

	public void setSiteApp(boolean siteApp) {
		this.siteApp = siteApp;
	}

	public Set getCodeAcceses() {
		return this.codeAcceses;
	}

	public void setCodeAcceses(Set codeAcceses) {
		this.codeAcceses = codeAcceses;
	}

	public Set getMarchandEntreprises() {
		return this.marchandEntreprises;
	}

	public void setMarchandEntreprises(Set marchandEntreprises) {
		this.marchandEntreprises = marchandEntreprises;
	}

	public Set getMarchandAssociations() {
		return this.marchandAssociations;
	}

	public void setMarchandAssociations(Set marchandAssociations) {
		this.marchandAssociations = marchandAssociations;
	}

}
