package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * MarchandAssociation generated by hbm2java
 */
public class MarchandAssociation implements java.io.Serializable {

	private MarchandAssociationId id;
	private Marchand marchand;

	public MarchandAssociation() {
	}

	public MarchandAssociation(MarchandAssociationId id, Marchand marchand) {
		this.id = id;
		this.marchand = marchand;
	}

	public MarchandAssociationId getId() {
		return this.id;
	}

	public void setId(MarchandAssociationId id) {
		this.id = id;
	}

	public Marchand getMarchand() {
		return this.marchand;
	}

	public void setMarchand(Marchand marchand) {
		this.marchand = marchand;
	}

}
