package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * MarchandEntreprise generated by hbm2java
 */
public class MarchandEntreprise implements java.io.Serializable {

	private MarchandEntrepriseId id;
	private Marchand marchand;

	public MarchandEntreprise() {
	}

	public MarchandEntreprise(MarchandEntrepriseId id, Marchand marchand) {
		this.id = id;
		this.marchand = marchand;
	}

	public MarchandEntrepriseId getId() {
		return this.id;
	}

	public void setId(MarchandEntrepriseId id) {
		this.id = id;
	}

	public Marchand getMarchand() {
		return this.marchand;
	}

	public void setMarchand(Marchand marchand) {
		this.marchand = marchand;
	}

}
