package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * Paiement generated by hbm2java
 */
public class Paiement implements java.io.Serializable {

	private Integer idPaiement;
	private int idPays;
	private String serviceOp;
	private String numeroOp;
	private double gainOpe;

	public Paiement() {
	}

	public Paiement(int idPays, String serviceOp, String numeroOp,
			double gainOpe) {
		this.idPays = idPays;
		this.serviceOp = serviceOp;
		this.numeroOp = numeroOp;
		this.gainOpe = gainOpe;
	}

	public Integer getIdPaiement() {
		return this.idPaiement;
	}

	public void setIdPaiement(Integer idPaiement) {
		this.idPaiement = idPaiement;
	}

	public int getIdPays() {
		return this.idPays;
	}

	public void setIdPays(int idPays) {
		this.idPays = idPays;
	}

	public String getServiceOp() {
		return this.serviceOp;
	}

	public void setServiceOp(String serviceOp) {
		this.serviceOp = serviceOp;
	}

	public String getNumeroOp() {
		return this.numeroOp;
	}

	public void setNumeroOp(String numeroOp) {
		this.numeroOp = numeroOp;
	}

	public double getGainOpe() {
		return this.gainOpe;
	}

	public void setGainOpe(double gainOpe) {
		this.gainOpe = gainOpe;
	}

}
