package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pays generated by hbm2java
 */
public class Pays implements java.io.Serializable {

	private Integer idPays;
	private String nomPays;
	private Set serviceAuthPayses = new HashSet(0);

	public Pays() {
	}

	public Pays(String nomPays) {
		this.nomPays = nomPays;
	}

	public Pays(String nomPays, Set serviceAuthPayses) {
		this.nomPays = nomPays;
		this.serviceAuthPayses = serviceAuthPayses;
	}

	public Integer getIdPays() {
		return this.idPays;
	}

	public void setIdPays(Integer idPays) {
		this.idPays = idPays;
	}

	public String getNomPays() {
		return this.nomPays;
	}

	public void setNomPays(String nomPays) {
		this.nomPays = nomPays;
	}

	public Set getServiceAuthPayses() {
		return this.serviceAuthPayses;
	}

	public void setServiceAuthPayses(Set serviceAuthPayses) {
		this.serviceAuthPayses = serviceAuthPayses;
	}

}
