package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * ServiceAuthPays generated by hbm2java
 */
public class ServiceAuthPays implements java.io.Serializable {

	private ServiceAuthPaysId id;
	private Pays pays;
	private TypeService typeService;

	public ServiceAuthPays() {
	}

	public ServiceAuthPays(ServiceAuthPaysId id, Pays pays,
			TypeService typeService) {
		this.id = id;
		this.pays = pays;
		this.typeService = typeService;
	}

	public ServiceAuthPaysId getId() {
		return this.id;
	}

	public void setId(ServiceAuthPaysId id) {
		this.id = id;
	}

	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	public TypeService getTypeService() {
		return this.typeService;
	}

	public void setTypeService(TypeService typeService) {
		this.typeService = typeService;
	}

}
