package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private Integer idService;
	private CodeService codeService;
	private TypeService typeService;
	private String nomService;
	private String codeTest;
	private boolean valide;
	private int cout;
	private Set abonnements = new HashSet(0);
	private Set serviceDistants = new HashSet(0);

	public Service() {
	}

	public Service(CodeService codeService, TypeService typeService,
			String nomService, String codeTest, boolean valide, int cout) {
		this.codeService = codeService;
		this.typeService = typeService;
		this.nomService = nomService;
		this.codeTest = codeTest;
		this.valide = valide;
		this.cout = cout;
	}

	public Service(CodeService codeService, TypeService typeService,
			String nomService, String codeTest, boolean valide, int cout,
			Set abonnements, Set serviceDistants) {
		this.codeService = codeService;
		this.typeService = typeService;
		this.nomService = nomService;
		this.codeTest = codeTest;
		this.valide = valide;
		this.cout = cout;
		this.abonnements = abonnements;
		this.serviceDistants = serviceDistants;
	}

	public Integer getIdService() {
		return this.idService;
	}

	public void setIdService(Integer idService) {
		this.idService = idService;
	}

	public CodeService getCodeService() {
		return this.codeService;
	}

	public void setCodeService(CodeService codeService) {
		this.codeService = codeService;
	}

	public TypeService getTypeService() {
		return this.typeService;
	}

	public void setTypeService(TypeService typeService) {
		this.typeService = typeService;
	}

	public String getNomService() {
		return this.nomService;
	}

	public void setNomService(String nomService) {
		this.nomService = nomService;
	}

	public String getCodeTest() {
		return this.codeTest;
	}

	public void setCodeTest(String codeTest) {
		this.codeTest = codeTest;
	}

	public boolean isValide() {
		return this.valide;
	}

	public void setValide(boolean valide) {
		this.valide = valide;
	}

	public int getCout() {
		return this.cout;
	}

	public void setCout(int cout) {
		this.cout = cout;
	}

	public Set getAbonnements() {
		return this.abonnements;
	}

	public void setAbonnements(Set abonnements) {
		this.abonnements = abonnements;
	}

	public Set getServiceDistants() {
		return this.serviceDistants;
	}

	public void setServiceDistants(Set serviceDistants) {
		this.serviceDistants = serviceDistants;
	}

}
