package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * ServiceDistant generated by hbm2java
 */
public class ServiceDistant implements java.io.Serializable {

	private ServiceDistantId id;
	private Service service;

	public ServiceDistant() {
	}

	public ServiceDistant(ServiceDistantId id, Service service) {
		this.id = id;
		this.service = service;
	}

	public ServiceDistantId getId() {
		return this.id;
	}

	public void setId(ServiceDistantId id) {
		this.id = id;
	}

	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

}
