package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

/**
 * ServiceAuthPaysId generated by hbm2java
 */
public class ServiceAuthPaysId implements java.io.Serializable {

	private int idTypeservice;
	private int idPays;

	public ServiceAuthPaysId() {
	}

	public ServiceAuthPaysId(int idTypeservice, int idPays) {
		this.idTypeservice = idTypeservice;
		this.idPays = idPays;
	}

	public int getIdTypeservice() {
		return this.idTypeservice;
	}

	public void setIdTypeservice(int idTypeservice) {
		this.idTypeservice = idTypeservice;
	}

	public int getIdPays() {
		return this.idPays;
	}

	public void setIdPays(int idPays) {
		this.idPays = idPays;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiceAuthPaysId))
			return false;
		ServiceAuthPaysId castOther = (ServiceAuthPaysId) other;

		return (this.getIdTypeservice() == castOther.getIdTypeservice())
				&& (this.getIdPays() == castOther.getIdPays());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTypeservice();
		result = 37 * result + this.getIdPays();
		return result;
	}

}
