package com.DialPass.dao;

// Generated 25 févr. 2014 21:26:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TypeService generated by hbm2java
 */
public class TypeService implements java.io.Serializable {

	private Integer idTypeservice;
	private String typeservice;
	private Set services = new HashSet(0);
	private Set serviceAuthPayses = new HashSet(0);

	public TypeService() {
	}

	public TypeService(String typeservice) {
		this.typeservice = typeservice;
	}

	public TypeService(String typeservice, Set services, Set serviceAuthPayses) {
		this.typeservice = typeservice;
		this.services = services;
		this.serviceAuthPayses = serviceAuthPayses;
	}

	public Integer getIdTypeservice() {
		return this.idTypeservice;
	}

	public void setIdTypeservice(Integer idTypeservice) {
		this.idTypeservice = idTypeservice;
	}

	public String getTypeservice() {
		return this.typeservice;
	}

	public void setTypeservice(String typeservice) {
		this.typeservice = typeservice;
	}

	public Set getServices() {
		return this.services;
	}

	public void setServices(Set services) {
		this.services = services;
	}

	public Set getServiceAuthPayses() {
		return this.serviceAuthPayses;
	}

	public void setServiceAuthPayses(Set serviceAuthPayses) {
		this.serviceAuthPayses = serviceAuthPayses;
	}

}
